### ISSUE TITLE
测试benchmark的设置方法

### ISSUE THREAD

**Issue by Wucy0519** [mulns/PerVFI#3]
抱歉打扰到您。我们想知道您在测试各个benchmark时候，如DAVIS，获取LPIPS使用的网络模型是什么？其次是DAVIS数据集的测试规则我们没有找到，您可以提供一下benchmark的测试代码嘛

**Comment by mulns** [comment]
请参考[VFIBenchmark](https://img.shields.io/badge/CVPR2024-PDF-b31b1b)，我们提供了用于测试的script。如果有进一步的问题可以再联系我

**Comment by Wucy0519** [comment]
好的，谢谢您
