### ISSUE TITLE
在Vimeo90K上的测试结果问题

### ISSUE THREAD

**Issue by Wucy0519** [mulns/PerVFI#4]
您好，我们将您的算法PerVFI在Vimeo90k的测试集上进行了重新测试，与论文中的PSNR和LPIPS均有不同，我们猜测是我们测试lpips的所用的模型不同，PSNR测量数值有0.05db的差异

**Comment by mulns** [comment]
请参考[VFIBenchmark](https://img.shields.io/badge/CVPR2024-PDF-b31b1b)，我们提供了用于测试的script。

**Comment by Wucy0519** [comment]
好的，谢谢您
